define_instruction_class! {
    AluInstruction {
        Lui(Lui),
        Auipc(Auipc),
        Addi(Addi),
        Slti(Slti),
        Sltiu(Sltiu),
        Xori(Xori),
        Ori(Ori),
        Andi(Andi),
        Slli(Slli),
        Srli(Srli),
        Srai(Srai),
        Add(Add),
        Sub(Sub),
        Sll(Sll),
        Slt(Slt),
        Sltu(Sltu),
        Xor(Xor),
        Srl(Srl),
        Sra(Sra),
        Or(Or),
        And(And),
    }
}
