[meta]
name = "Insert_name_here"
description = "Insert description here"
extends = ""

[meta.types.xreg]
max_bits = 5
enumerate = [
    "zero", "ra",  "sp",  "gp", "tp", "t0", "t1", "t2",
      "fp", "s1",  "a0",  "a1", "a2", "a3", "a4", "a5",
      "a6", "a7",  "s2",  "s3", "s4", "s5", "s6", "s7",
      "s8", "s9", "s10", "s11", "t3", "t4", "t5", "t6",
]

# [meta.types.opcode]
# bits = 7

[meta.formats.r]
encoding = [
    { name = "funct7", bits = 7                  },
    { name = "rs2",    bits = 5, type = "xreg"   },
    { name = "rs1",    bits = 5, type = "xreg"   },
    { name = "funct3", bits = 3                  },
    { name = "rd",     bits = 5, type = "xreg"   },
    { name = "opcode", bits = 7, type = "opcode" },
]

[instructions.encoding]

add   = { format = "r", opcode = "0110011", funct3 = "000", funct7 = "0000000" }

[instructions.asm]

add   = { mnemonic = "add", fields = [ "rd", "rs1", "rs2" ] }
